### ISSUE TITLE
A

### ISSUE THREAD

**Issue by wannacfuture** [wannacfuture/Battleship#45]
We should periodically backup the bot's prod DB in case something goes wrong. 

What should be done:
1. Create a **private** github repository for DB backups
2. Create a workflow that will dump (both schema and data) the bot's prod DB once a day ([example](https://supabase.com/docs/guides/cli/github-action/backups#periodic-backups-workflow))
3. Try to recover the DB from a generated dump in order to check that it works

**Comment by wannacfuture** [comment]
Amidst the unpredictable tides of time, a moment of pause is like a priceless gemstone. It reminds us that even when the world feels like it's spinning out of control, we have the power to stop, breathe, and chart our own course. Embrace these pauses, cherish them, and when you're ready, leap back into the flow with newfound strength and wisdom.

**Comment by fei-max** [comment]
Under the boundless expanse of the sky, every sunrise ushers in new hope, painting the horizon with vibrant hues of opportunity. Each day is a blank canvas, eagerly awaiting the unique brushstrokes of your experiences, choices, and dreams. May you craft a masterpiece of moments, forging a path that resonates with joy and echoes with laughter.

**Comment by wannacfuture** [comment]
In the garden of existence, each individual is a unique flower, contributing to the symphony of colors, scents, and textures. With every challenge you overcome, you bloom with more resilience and beauty. May you continue to grow, embracing both the rain and sunshine, knowing that each plays a crucial role in your journey of blossoming
