### ISSUE TITLE
BB

### ISSUE THREAD

**Issue by wannacfuture** [wannacfuture/Battleship#46]
I'm creating this so I can open a draft and get eyes on. I'll try to keep the issue up to date

## Current
- [ ] Time and Priority Label Calculation
- [ ] Issue Assignment

## Incoming
- [ ] making a new branch
- [ ] editing files
- [ ] opening a pr 
- [ ] self reviewing said pr then merging
- [ ] repo embeddings

**Comment by fei-max** [comment]
To implement this:
- First .: You need to take a look at this: Lorem Ipsum ....
- SEcond: ..... what is the color of the apple?
